export const GET_TOP_HEADLINES_REQUEST = 'GET_TOP_HEADLINES_REQUEST'
export const GET_TOP_HEADLINES_SUCCESS = 'GET_TOP_HEADLINES_SUCCESS'
export const GET_TOP_HEADLINES_FAILURE = 'GET_TOP_HEADLINES_FAILURE'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'
